services:
  energy-generator:
    build:
      context: ../
      dockerfile: docker/energy-generator/Dockerfile
    volumes:
      - ../src/energy-generator:/app
      - ../data:/data

  energy-analyzer:
    build:
      context: ../
      dockerfile: docker/energy-analyzer/Dockerfile
    volumes:
      - ../src/energy-analyzer:/app
      - ../data:/data
    depends_on:
      - energy-generator

  report-generator:
    build:
      context: ../
      dockerfile: docker/report-generator/Dockerfile
    volumes:
      - ../src/report-generator:/app
      - ../data:/data
    depends_on:
      - energy-analyzer